//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDialgaTeam.FossilFighters.Tool.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheDialgaTeam.FossilFighters.Tool.Cli.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing: {0}.
        /// </summary>
        internal static string CompressCommand_Compress_Compressing_File {
            get {
                return ResourceManager.GetString("CompressCommand_Compress_Compressing_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress files into MAR archive..
        /// </summary>
        internal static string CompressCommandDescription {
            get {
                return ResourceManager.GetString("CompressCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress MAR archives into raw binary files..
        /// </summary>
        internal static string DecompressCommandDescription {
            get {
                return ResourceManager.GetString("DecompressCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Nds file... This may take a while..
        /// </summary>
        internal static string ExtractingNdsFile {
            get {
                return ResourceManager.GetString("ExtractingNdsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted: {0} to {1}.
        /// </summary>
        internal static string FileConvertedFromTo {
            get {
                return ResourceManager.GetString("FileConvertedFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted: {0}.
        /// </summary>
        internal static string FileExtracted {
            get {
                return ResourceManager.GetString("FileExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting: {0}.
        /// </summary>
        internal static string FileExtracting {
            get {
                return ResourceManager.GetString("FileExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is used to decompress and compress MAR archives used in Fossil Fighters game..
        /// </summary>
        internal static string FossilFightersToolDescription {
            get {
                return ResourceManager.GetString("FossilFightersToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; does not exists..
        /// </summary>
        internal static string InputDoesNotExists {
            get {
                return ResourceManager.GetString("InputDoesNotExists", resourceCulture);
            }
        }
    }
}
